# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter cupidr ice lemonade lemonadep lunaa martini porsche ziti,$(TARGET_DEVICE)),)

endif
