# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter cupid martini OP524F RMX3312 RMX3360 RMX3461,$(TARGET_DEVICE)),)

endif
